language: perl
matrix:
  include:
    - perl: "5.8"
      dist: trusty
    - perl: "5.10"
      dist: trusty
    - perl: "5.16"
      dist: trusty
    - perl: "5.30"
install:
  - curl -sSL --compressed https://git.io/cpm | perl - install -g --with-develop
script:
  - prove -l t xt
